#!/usr/bin/env bash

# I'm sick of reading bazel docs so i'm doing this the hard? way.
# there's probably an easy way to get bazel to do this but i'm not figuring
# it out right now.


# first build the jars with bazel
npx @bazel/bazelisk build --copt "-O3" --config=clang //java/...

# then manually copy them into your local maven repo
version=LOCAL-SNAPSHOT
names="client jni_channel_darwin jni_channel_linux jni_channel types"
source=./bazel-bin/java/com/google/zetasql

for name in $names
do
  mvn install:install-file \
    -Dversion=${version} \
    -Dfile=$source/${name}_jar.jar \
    -DpomFile=$source/${name}_pom.xml
done
  
